
name: cicd-demo

on:
  push:
    branches:
      - '*'

env:
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: "Start build job"
        run: echo "Starting the build job."

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: "hostname-node-app"
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Docker Build
        id: docker-build
        run: |
          docker build -t fra.ocir.io/fr1ie1pznths/hostname-node-app:latest .

      - name: Docker Push
        id: docker-push
        run: |
          docker push fra.ocir.io/fr1ie1pznths/hostname-node-app:latest

  deploy-job:
    name: Deploy Job
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: Start deploy job
        run: echo "Starting the deploy job."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        id: kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Run Kubectl
        run: kubectl apply -f app-delpoy.yaml

